# config.yaml

ticker: "NVDA"
dates:
  start: '2019-01-01'
  end: '2024-06-01'
  train_start: '2019-01-01'
  train_end: '2023-01-01'
  val_start: '2023-01-02'
  val_end: '2024-01-01'
  test_start: '2024-01-02'
  test_end: '2024-06-01'

sequence_size: 60
scaler_save_path: "models/nvda_scaler.gz"

# Model training parameters
model_training:
  model_path: "models/nvda_model.model.keras"
  epochs: 80
  batch_size: 64

